version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'Crud'
      MYSQL_USER: 'Admin'
      MYSQL_PASSWORD: '65544aA!'
      MYSQL_ROOT_PASSWORD: '65544aA!'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
    volumes:
      - crud:/var/lib/mysql
    
  nodejs:
   image: luis2200/lab5.1
   ports:
      - '3307:3306'
      - '8000:8000'
   expose:
      - '8000'
   depends_on:
     - db
   networks:
      vpcbr:
        ipv4_address: 10.5.0.6
# Names our volume
volumes:
  crud:
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         